@startuml Clases

Producto               "1    "      *--       "0..*   "        Inventario
Catalogo               "1..*  "      --        "1..*  "        Producto
      
Cliente                "1   "        --         "0..*"         Factura
Factura                "1   "        --         "1..* "        DetalleFactura
DetalleFactura         "1..*   "     --       "1 "             Producto
      
Empleado               "1 "          --       "1..*   "        FacturaCompraProveedor
FacturaCompraProveedor "1"           --       "1..* "          DetalleCompraProveedor

'Esto es la relacion de las personas'
Persona   <|--           Empleado
Persona   <|---left      Cliente
Persona   <|---right     Proveedor

'Relaciones basicas entre las personas'
Proveedor   "1   "     o--    "1..*  "   Catalogo
Empleado    "1   "     o--    "1   "     Cargo
Cliente     "1   "     *--    "1   "     NitCliente

class Inventario {
    CodigoInventario : int
    codigoProducto   : int
    nombreProducto   : String
    cantidadStock    : int
    stockMinimo      : int
    stockMaximo      : int
    cantidadOrden    : int
    precioCompra     : double
    precioVenta      : double

    TamañoPorProducto()
    TamañoGeneral()
    CalculoVenta()
    CalculoCompra()
}

class Producto {
    codigoProducto : int
    nombreProducto : String

    getProduct()
    setProduct()
}

abstract class Persona {
    codigoPersona  : int
    nombrePersona  : String
    direccion      : String
    telefono       : String

    getPerson()
    setPerson()
}

class Empleado {
    codigoEmpleado : int
    cargoEmpleado  : int

    getEmpleado()
    getCargo()
}

class Cargo {
    codigoCargo    : int
    nombreCargo    : String
    descripcion    : String

    getCargo()
    setCargo()
}

class Cliente {
    codigoCliente  : int
    nitCliente     : int

    getCliente()
    setCliente()
}

class Proveedor {
    codigoProveedor : int

    getProveedor()
    setProveedor()
}

class Catalogo {
    codigoCatalogo : int

    getCatalogo()
    setCatalogo()
}

class NitCliente {
    nitCliente     : int

    getNitCliente()
    setNitCliente()
}

class Factura {
    codigoFactura  : int
    codigoCliente  : int
    fecha          : Date
    montoTotal     : double
}

class DetalleFactura {
    codigoDetalleFactura : int
    codigoProducto       : int
    cantidad             : int
    precio: double
}

class FacturaCompraProveedor {
    codigoFactura   : int
    codigoProveedor : int
    codigoCatalogo  : int
    montoTotal      : double
}

class DetalleCompraProveedor {
    codigoProveedor: int
    codigoCatalogo : int
    codigoProducto : int
    cantidad       : int
    precio         : double
}

@enduml